---
# Playbook to deploy splunk on existing machines
# Relevant vars can be found in root_vars/splunk_deployment_vars.yml
- name: Deploy splunk
  hosts: splunk_servers

  vars_files:
    - root_vars/splunk_deployment_vars.yml
    - root_vars/ec2_image_vars.yml 
  tasks:
    - name: Base install of Splunk
      include_role:
        name: "splunk_common"
      when: splunk_setup|bool  
      tags: "phantom-app-config"