---
# Playbook to configure phantom servers with demo settings
# Relevant vars can be found in root_vars/phantom_setup_vars.yml
- name: Setup phantom server
  hosts: phantom_servers

  vars_files:
    - root_vars/phantom_setup_vars.yml
    - root_vars/ec2_image_vars.yml
  tasks:
    - name: Phantom servers setup
      include_role:
        name: "phantom"
      when: phantom_init|bool  
      tags: phantom-demo