---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - root_vars/ec2_credentials_vars.yml  
    - root_vars/ec2_image_vars.yml  
  pre_tasks:
    - name: Ensure boto and boto3 modules are installed
      pip:
        name: ['boto3', 'boto', 'botocore']


  module_defaults:
    ec2_group:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    ec2_instance_facts:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"

  tasks:

    - name: Provision EC2 Instance
      include_role:
        name: "ec2_create"
      tags: info

    - meta: refresh_inventory

    # Restart it to get the right password
    - name: Restart phantom instance(s)
      ec2:
        region: "{{ region }}"
        instance_tags:
          Name: "{{ phantom_aws.instance_name_tag }}"
        state: restarted

    - pause: 
        minutes: 1
        prompt: "Give phantom some time to initiate"

    # Wait for Phantom especially to come up
    - name: Wait for SSH to come up
      delegate_to: "{{ item }}"
      wait_for_connection:
        delay: 30
        timeout: 160
      loop: "{{ groups['all'] }}"
 

- import_playbook: wait.yml

#Base setup of centos OS stuff
- import_playbook: base_setup.yml

#Splunk install
- import_playbook: deploy_splunk.yml
  when: splunk_init|bool




