---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - root_vars/ec2_credentials_vars.yml  
    - root_vars/ec2_image_vars.yml  
  pre_tasks:
    - name: Ensure boto and boto3 modules are installed
      pip:
        name: ['boto3', 'boto', 'botocore']


  module_defaults:
    ec2_group:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    ec2_instance_facts:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"

  tasks:
    - name: Provision EC2 Instance
      include_role:
        name: "ec2_create"
      tags: info

    # - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    #   wait_for:
    #     port: 22
    #     host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    #     search_regex: OpenSSH
    #     delay: 10
    #   vars:
    #     ansible_connection: local
    - meta: refresh_inventory

#Base setup of centos OS stuff
- import_playbook: base_setup.yml

#Splunk install 
- import_playbook: deploy_splunk.yml
  when: splunk_setup|bool




