---
# This is the default playbook for RDAP

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - root_vars/ec2_credentials_vars.yml  
    - root_vars/ec2_image_vars.yml  
  pre_tasks:
    - name: Ensure boto and boto3 modules are installed
      pip:
        name: ['boto3', 'boto', 'botocore']


  module_defaults:
    ec2_group:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    ec2_instance_facts:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"

  tasks:

# Create EC2 images 

    - name: Provision EC2 Instance
      include_role:
        name: "ec2_create"
      tags: info

    - meta: refresh_inventory


- import_playbook: wait.yml

#Base setup of centos OS stuff

- import_playbook: base_setup.yml

# Install SPlunk
- import_playbook: deploy_splunk.yml
  when: splunk_init|bool
  
- import_playbook: phantom_setup.yml
  when: phantom_setup|bool
  tags: phantom-demo





