---

- hosts: all
  gather_facts: false
  vars_files:
    - root_vars/ec2_image_vars.yml 

  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        timeout: 160