---
# Just wait for SSH to come up on all hosts. This does not necessarily mean the service 
# running on the host is also ok. Ansible wait_for is more suitable but has proven buggy

- hosts: all
  gather_facts: false
  vars_files:
    - root_vars/ec2_image_vars.yml 

  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 20
        timeout: 260
