---
# This will add the /var/log/secure to the list of monitored sources

- name: Monitor local secure log
  command: "{{ splunk.exec }} add monitor -source /var/log/secure -auth admin:{{ splunk.password }}"
  ignore_errors: true