---
- name: Register splunk init file on remote
  stat:
    path: ~/splunk_installed
  register: splunk_installed_flag

- name: Download splunk main software
  get_url: 
    url: "{{ splunk.main_download_url }}"
    dest: "{{ splunk.main_out_file }}"
    checksum: md5:ac6f332dc37845e5d68516233cf8dc8e
  when: splunk_installed_flag.stat.exists == False 

- name: Unzip Splunk
  unarchive:
    src: "{{ splunk.main_out_file }}"
    dest: "{{ splunk.install_dir }}"
    remote_src: yes
  when: splunk_installed_flag.stat.exists == False

- name: Remove passwd file
  file:
    path: "{{ splunk.home }}/etc/passwd"
    state: absent
  when: splunk_installed_flag.stat.exists == False     

- name: Generate user-seed.conf
  copy:
    dest: "{{ splunk.home }}/etc/system/local/user-seed.conf"
    content: |
      [user_info]
      PASSWORD = {{ splunk.password }}
  when: splunk_installed_flag.stat.exists == False       

- name: Set init file
  file:
    path: ~/splunk_installed
    state: touch
  when: splunk_installed_flag.stat.exists == False     

# For some reason the restart handlers dont always work so we need to do 
# manual start/stop

- include_tasks: stop_splunk.yml

- include_tasks: enable_s2s_port.yml

- include_tasks: start_splunk.yml

- include_tasks: add_splunk_license.yml
  when: splunk_license_included| bool

- include_tasks: set_as_hec_receiver.yml


- include_tasks: install_apps_git.yml
  vars:
    app_file: "{{ item }}"
  loop: "{{ splunk.apps }}"
  when: splunk.install_apps_git|bool
  notify:
    - Restart the splunkd service

- include_tasks: install_app.yml
  vars:
    app_file: "{{ item }}"
  loop: "{{ splunk.apps }}"
  when: splunk.install_apps|bool
  notify:
    - Restart the splunkd service

- include_tasks: install_es.yml
  when: splunk.install_es|bool
  notify:
    - Restart the splunkd service

# The handlers for restart ar buggy and dont work most of the times
- include_tasks: stop_splunk.yml 
- include_tasks: start_splunk.yml

- include_tasks: add_local_monitor.yml

- include_tasks: add_infra_local_entity.yml

- include_tasks: splunk_phantom_config.yml
  tags: phantom-app-config
  when: splunk_phantom_setup|bool





