---

- name: Check if Splunk is running
  shell: ps -ef |  grep splunkd | grep -v grep
  register: process_list
  ignore_errors: true
  changed_when: false  

# Race condition
- name: Start Splunk v2
  command: "{{ splunk.exec }} start --accept-license --answer-yes --no-prompt"
  when: process_list.rc != 0 or "process_list.stdout.find('restart') == 1"    
  register: splunk_status
