---
## Install base packages

- name: Copy htpdate
  copy:
    src: roles/ec2_base_setup/files/htpdate-1.1.0-1.el7.rf.x86_64.rpm
    dest: /tmp
    remote_src: false
    mode: preserve
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install htpdate
  yum:
    name: /tmp/htpdate-1.1.0-1.el7.rf.x86_64.rpm
    update_cache: yes
    state: present
  become: yes
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  
- name: Setup time sync with Amazon
  cron:
    name: "Htpdate AWS"
    minute: "0"
    hour: "1"
    job: "htpdate -D www.amazon.com"  
    state: present
  become: yes
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  
- name: Ensure basic list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
  become: yes
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Change permission on var/log/secure for Centos user   
  file:
    path: /var/log/secure
    owner: centos
  become: yes
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#- name: Reboot Phantom servers
- name: Reboot Phantom server
  delegate_to: "{{ group[phantom_servers][0] }}"
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

# Fix the locale problem on centos as it creates problem with phantom when installing certs and restarting
# vi /etc/environment

# add these lines...

# LANG=en_US.utf-8
# LC_ALL=en_US.utf-8
