---

      
- name: Test ping
  action: ping

- include_tasks: ec2_splunk.yml
  when: splunk_init|bool

- include_tasks: ec2_phantom.yml
  when: phantom_init|bool

- include_tasks: ec2_instance_info.yml
  tags:
    - info
    - phantom-app-config 